JOOMLA_DB = '' #Joomla database Name
JOOMLA_USER = ''
JOOMLA_PASS = ''
JOOMLA_HOST = ''
JOOMLA_PREFIX = ''

WORDPRESS_DB = ''
WORDPRESS_USER = ''
WORDPRESS_PASS = ''
WORDPRESS_HOST = ''
WORDPRESS_PREFIX = ''
